#theme: jekyll-theme-merlot

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

base-url: https://TechnoPagan87109.github.io/Haven
